### ISSUE TITLE
Add ability to identify if TEs in reference genome are present in sample

### ISSUE THREAD

**Issue by cbergman** [bergmanlab/ngs_te_mapper#11]

**Comment by raquels95** [comment]
ngs_te_mapper currently first finds TE-junction (split) reads by aligning to the TE fasta database. Then it aligns unmodified versions of these reads to the reference genome and looks for places where these reads align fully to the genome. This first step is similar to the way non-reference insertions are found. TE-junction read clusters are then used to identify the start or end of reference TE on the basis of where the TE maps in the read vs TE database. TE-junction read clusters from TE-starts are matched locally to TE-junction read clusters from TE-ends within a 100 bp window. Like a non-reference TE, reference TEs must have a match to both the start and the end of the TE sequence in the TE DB.

ngs_te_mapper does not use a TE annotation of the of the refernece genome to find reference insertions in your sample. This could be implemented, but would require changing the reference TE process.
