### ISSUE TITLE
Add support to use blasr or bwa mem as mapping engine for PacBio reads

### ISSUE THREAD

**Issue by cbergman** [bergmanlab/ngs_te_mapper#8]
BLASR code is on github here: https://github.com/PacificBiosciences/blasr

**Comment by nelson42** [comment]
- unsing current version of bwa mem:
```
bwa mem -x pacbio ref.fa reads.fq > aln.sam
```
- -x pacbio parameters are described here: https://www.biostars.org/p/111798/#111823
